### ISSUE TITLE
TweakmProPlace doesnt work properly with Flexible Block Placement

### ISSUE THREAD

**Issue by HellyTubbies** [Fallen-Breath/tweakermore#26]
## QOL to TWEAKMPROPLACE
TweakmProPlace's new rotation check doesn't properly support Flexible Block Placement whilst accurate block placement works fine alongside ProPlace.

## To Reproduce

1. Attempt to use Flexible Block Placement options, example: rotation, offset, and adjacent.  

What you expect to see: being able to use Flexible alongside ProPlace without getting a debug/error for "not placing it towards a direction".

What actually happens: Error text/debug appears reminding the user that it is not possible to place the block with TweakmProPlace enabled whilst using Flexible Block Placement.

## Environment
- Minecraft version: '1.19.3, 1.19.2'
- TweakerMore version: '3.8+'

**Comment by Fallen-Breath** [comment]
try this build https://github.com/Fallen-Breath/tweakermore/actions/runs/3862525360

**Comment by HellyTubbies** [comment]
Didn't work for me for some reason. could it be my mods running?
Crash Log:
[23:31:45] [Render thread/ERROR]: Mixin apply for mod tweakermore failed tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> net.minecraft.class_437: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on fixHoverTextScale_storeLocals could not find any targets matching 'Lnet/minecraft/class_437;method_32633(Lnet/minecraft/class_4587;Ljava/util/List;II)V' in net.minecraft.class_437. Using refmap tweakermore-mc1.19.2-refmap.json [PREINJECT Applicator Phase -> tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> Prepare Injections ->  -> handler$eof000$fixHoverTextScale_storeLocals(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V -> Parse] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on fixHoverTextScale_storeLocals could not find any targets matching 'Lnet/minecraft/class_437;method_32633(Lnet/minecraft/class_4587;Ljava/util/List;II)V' in net.minecraft.class_437. Using refmap tweakermore-mc1.19.2-refmap.json [PREINJECT Applicator Phase -> tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> Prepare Injections ->  -> handler$eof000$fixHoverTextScale_storeLocals(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V -> Parse] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[minecraft-1.19.3-client.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?] [23:31:46] [Render thread/ERROR]: Mixin apply for mod tweakermore failed tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> net.minecraft.class_437: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on fixHoverTextScale_storeLocals could not find any targets matching 'Lnet/minecraft/class_437;method_32633(Lnet/minecraft/class_4587;Ljava/util/List;II)V' in net.minecraft.class_437. Using refmap tweakermore-mc1.19.2-refmap.json [PREINJECT Applicator Phase -> tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> Prepare Injections ->  -> handler$eof000$fixHoverTextScale_storeLocals(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V -> Parse] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on fixHoverTextScale_storeLocals could not find any targets matching 'Lnet/minecraft/class_437;method_32633(Lnet/minecraft/class_4587;Ljava/util/List;II)V' in net.minecraft.class_437. Using refmap tweakermore-mc1.19.2-refmap.json [PREINJECT Applicator Phase -> tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> Prepare Injections ->  -> handler$eof000$fixHoverTextScale_storeLocals(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V -> Parse] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.3-client.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?] [23:31:46] [Render thread/ERROR]: Minecraft has crashed! net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?] 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?] 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.3-client.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?] 	... 5 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.3-client.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?] 	... 5 more Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore] from phase [DEFAULT] in config [tweakermore.mixins.json] FAILED during APPLY 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.3-client.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?] 	... 5 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on fixHoverTextScale_storeLocals could not find any targets matching 'Lnet/minecraft/class_437;method_32633(Lnet/minecraft/class_4587;Ljava/util/List;II)V' in net.minecraft.class_437. Using refmap tweakermore-mc1.19.2-refmap.json [PREINJECT Applicator Phase -> tweakermore.mixins.json:tweaks.mc_tweaks.fixHoverTextScale.ScreenMixin from mod tweakermore -> Prepare Injections ->  -> handler$eof000$fixHoverTextScale_storeLocals(Lnet/minecraft/class_4587;Ljava/util/List;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;IIIII)V -> Parse] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.12.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.12.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] 	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.3-client.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.3-client.jar:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?] 	... 5 more Process exited with code 1.

**Comment by Fallen-Breath** [comment]
> Didn't work for me for some reason. could it be my mods running?

Yeah seems like there are mod conflictions with tweakermore v3.9. You can open a new issue for this

**Comment by HellyTubbies** [comment]
alrighty.

**Comment by HellyTubbies** [comment]
ive done some further testing disabling all mods (besides the obvious like malilib) and it appears to still continue crashing. I've looked at the crash log and it has to do with something text related / hover text related from what i've seen. Could this be from the hovertext reminder for whenever u turn on TweakmProPlace or when you do an action it cancels?

**Comment by Fallen-Breath** [comment]
The crash doesn't related to this issue or TweakmProPlace, as I said it's due to changes in tweakermore v3.9. I'll suggest to open a new issue for this

**Comment by Fallen-Breath** [comment]
Just checked the crash report again, I think you were using tweakermore for mc1.19.2 in mc 1.19.3, and this will be the reason of the crash

**Comment by HellyTubbies** [comment]
Oh I see. I thought the 1.19.x file would include 1.19.1+ my bad haha.

**Comment by HellyTubbies** [comment]
I've found an issue with the build u have made.
1: when using flexible block placement alongside proplace sometimes the block rotation will not work first try and will still validate that wrongful block placement even though it wasnt valid. placing it again however works fixes the issue, but when switching hotbar slots for another type of block it resets that data/info.

**Comment by Fallen-Breath** [comment]
try https://github.com/Fallen-Breath/tweakermore/actions/runs/4092457866/jobs/7057210093

**Comment by HellyTubbies** [comment]
works good. things like the block not rotating are fixed but the overall warning message isn't. the block requires you to do 2 inputs before it actually realizes that the input is corrrect.

**Comment by Fallen-Breath** [comment]
> works good. things like the block not rotating are fixed but the overall warning message isn't. block placement requires you to do 2 inputs before it actually realizes that the input is corrrect.

any example detailed steps to reproduce?

**Comment by HellyTubbies** [comment]
> > works good. things like the block not rotating are fixed but the overall warning message isn't. block placement requires you to do 2 inputs before it actually realizes that the input is corrrect.
> 
> any example detailed steps to reproduce?

yeah sure. ill edit a video to show off the visuals of it. i know the reproduction steps but not entirely the cause. ill get to that during editing.

**Comment by HellyTubbies** [comment]
Alright, done with the editing stuff. so heres the clips of it. I suggest u watch them individually instead of all at once cuz i did some very quick cutting.

clips: https://www.youtube.com/watch?v=c6JZQHWgjY0

and about reproducing it, it appears to be something to do with how things are being executed. whenever u place a block with a direction from my playtesting (observers, pistons, etc..) instead of validating around 60% of the time, it will fail and not properly place the block. it requires the player to try placing the block a second time to realize it's valid. and if the player hotbar slot has not been switched and ur still holding that block that has trouble rotating the issue doesn't happen again. however changing ur hotbar selection will reset it.

adding on to that, the invalid block rotation issue is still there. it's just much less likely to happen now. 
in litematica there is a bug report for easyplace which kinda has the same. so maybe it's in relation to litematica pickblock feature?

**Comment by Fallen-Breath** [comment]
> 

Thanks a lot from the video, so seems like it's the auto pick stuffs, I'll try to fix that

For the invalid block rotation thing, if it's caused by player rotating too fast it's not fix-able with vanilla, because it's just the server-side player rotation has not been updated yet. Maybe sending rotation packet might work but I won't do that cuz it's too hacky for me

**Comment by Fallen-Breath** [comment]
try https://github.com/Fallen-Breath/tweakermore/actions/runs/4165769170

since tweakeroo codes for the placement tweaks stuffs is quite a mess so I can't guarantee the fix can work 100%

**Comment by HellyTubbies** [comment]
seems to be partially stable now. ill close this for now and will reopen if anything happens.
