### ISSUE TITLE
Xaero pvp (1.21.3) is incompatible

### ISSUE THREAD

**Issue by MeeniMc** [Fallen-Breath/tweakermore#86]
### Bug description

```
[21:52:33] [Render thread/ERROR] (FabricLoader/Mixin) Mixin apply for mod tweakermore failed tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore -> xaero.common.minimap.waypoints.render.WaypointsIngameRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Implicit variable modifier injection failed in xaero/common/minimap/waypoints/render/WaypointsIngameRenderer::adjustCameraEntityForFreecam2 [INJECT_APPLY Applicator Phase -> tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore -> Apply Injections ->  -> Inject -> tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore->@ModifyVariable::adjustCameraEntityForFreecam2(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297;]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in xaero/common/minimap/waypoints/render/WaypointsIngameRenderer::adjustCameraEntityForFreecam2 [INJECT_APPLY Applicator Phase -> tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore -> Apply Injections ->  -> Inject -> tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore->@ModifyVariable::adjustCameraEntityForFreecam2(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297;]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:237) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:284) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:508) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1483) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/xaero.hud.minimap.Minimap.<init>(Minimap.java:42) ~[BetterPvP_24.6.2_Fabric_1.21.3.jar:?]
	at knot/xaero.common.minimap.MinimapInterface.<init>(MinimapInterface.java:18) ~[BetterPvP_24.6.2_Fabric_1.21.3.jar:?]
	at knot/xaero.common.HudMod.loadClient(HudMod.java:213) ~[BetterPvP_24.6.2_Fabric_1.21.3.jar:?]
	at knot/xaero.pvp.BetterPVP.loadClient(BetterPVP.java:37) ~[BetterPvP_24.6.2_Fabric_1.21.3.jar:?]
	at knot/xaero.pvp.BetterPVPFabric.loadClient(BetterPVPFabric.java:46) ~[BetterPvP_24.6.2_Fabric_1.21.3.jar:?]
	at knot/xaero.pvp.BetterPVPFabric.onInitializeClient(BetterPVPFabric.java:28) ~[BetterPvP_24.6.2_Fabric_1.21.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.16.9.jar:?]
	at knot/net.minecraft.class_310.<init>(class_310.java:482) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:248) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.injection.modify.InvalidImplicitDiscriminatorException: Found 0 candidate variables but exactly 1 is required.
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findImplicitLocal(LocalVariableDiscriminator.java:370) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findLocal(LocalVariableDiscriminator.java:341) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:228) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	... 32 more
```

### Steps to reproduce

1. 1.21.3 with Fabric Loader 0.16.9
2. tweakermore 3.22.0
3. xaerobetterpvp 24.6.2

### Actual behavior

Game crash on load

### Relevant logs

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-11-26 21:52:40
Description: Unexpected error

java.lang.RuntimeException: java.lang.RuntimeException: Mixin transformation of xaero.common.minimap.waypoints.render.WaypointsIngameRenderer failed
	at knot//xaero.common.PlatformContextFabric.preTryLoadLater(PlatformContextFabric.java:44)
	at knot//xaero.pvp.BetterPVPFabric.tryLoadLater(BetterPVPFabric.java:64)
	at net.minecraft.class_310.handler$hbg002$xaerobetterpvp$onTickStart(xaero/common/mixin/MixinMinecraftClient.java [xaerohud.mixins.json]:32)
	at knot//net.minecraft.class_310.method_1574(class_310.java)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Mixin transformation of xaero.common.minimap.waypoints.render.WaypointsIngameRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//xaero.hud.minimap.Minimap.<init>(Minimap.java:42)
	at knot//xaero.common.minimap.MinimapInterface.<init>(MinimapInterface.java:18)
	at knot//xaero.common.HudMod.loadClient(HudMod.java:213)
	at knot//xaero.pvp.BetterPVP.loadClient(BetterPVP.java:37)
	at knot//xaero.pvp.BetterPVPFabric.loadClient(BetterPVPFabric.java:46)
	at knot//xaero.pvp.BetterPVPFabric.onInitializeClient(BetterPVPFabric.java:28)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:482)
	at knot//net.minecraft.client.main.Main.main(Main.java:248)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore] from phase [DEFAULT] in config [tweakermore.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Implicit variable modifier injection failed in xaero/common/minimap/waypoints/render/WaypointsIngameRenderer::adjustCameraEntityForFreecam2 [INJECT_APPLY Applicator Phase -> tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore -> Apply Injections ->  -> Inject -> tweakermore.mixins.json:tweaks.mod_tweaks.xmapWaypointFreecamCompact.WorldMapSessionMixin from mod tweakermore->@ModifyVariable::adjustCameraEntityForFreecam2(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297;]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:237)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:284)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:508)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1483)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more
Caused by: org.spongepowered.asm.mixin.injection.modify.InvalidImplicitDiscriminatorException: Found 0 candidate variables but exactly 1 is required.
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findImplicitLocal(LocalVariableDiscriminator.java:370)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator.findLocal(LocalVariableDiscriminator.java:341)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:228)
	... 32 more
```

### Minecraft version

1.21.3

### TweakerMore version

3.22.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
Seems like the mod tweak `xmapWaypointFreecamCompact` is no longer needed with Xaeros's mod >= `24.6`, there's no more freecam issue with the waypoint rendering
